In [ ]:
# Gradient Descent for Linear Regression (multiple variables)
# Model: y_hat = X @ w + b
# Loss:  MSE = mean((y_hat - y)^2)
import numpy as np

np.set_printoptions(
    suppress=True,
    formatter={"float_kind": "{:0.6f}".format},
)

## Gradient Descent (Multiple Variables)

We learn two types of parameters:
- `w`: one weight per feature
- `b`: one bias/intercept term

At each epoch:
1. Predict: `y_hat = X @ w + b`
2. Error: `error = y_hat - y`
3. Gradients:
   - `dw = (1/m) * (X.T @ error)`
   - `db = (1/m) * sum(error)`
4. Update:
   - `w = w - lr * dw`
   - `b = b - lr * db`

This keeps the implementation vectorized, short, and easy to debug.

In [ ]:
# Tiny vectorization check (optional intuition)
X_demo = np.array([[1, 2], [3, 4]])
w_demo = np.array([0.5, 1.0])
b_demo = 0.2

print("X_demo shape:", X_demo.shape)
print("w_demo shape:", w_demo.shape)
print("prediction:", X_demo @ w_demo + b_demo)
print("w_demo transpose:", w_demo.T)

[[2 3]
 [4 5]]
[[2 4]
 [3 5]]
[[13 23]
 [23 41]]
[[ 6  9]
 [12 15]]


In [ ]:
def compute_mse(X, y, w, b):
    """Mean Squared Error for y_hat = X @ w + b."""
    # @ is dot product operator
    y_hat = X @ w + b
    return np.mean((y_hat - y) ** 2)


def gradient_step(X, y, w, b, lr):
    """One gradient descent step (vectorized)."""
    m = X.shape[0]
    error = (X @ w + b) - y

    dw = (1 / m) * (X.T @ error)
    db = (1 / m) * np.sum(error)

    w = w - lr * dw
    b = b - lr * db
    return w, b

In [ ]:
def gradient_descent(X, y, lr=0.01, epochs=1000, debug_every=100):
    """Train linear regression with explicit weights (w) and bias (b)."""
    m, n = X.shape

    w = np.zeros(n)
    b = 0.0

    for epoch in range(epochs):
        w, b = gradient_step(X, y, w, b, lr)

        # Simple educational debugging during learning
        if epoch % debug_every == 0 or epoch == epochs - 1:
            mse = compute_mse(X, y, w, b)
            print(f"epoch={epoch:4d} | mse={mse:10.6f} | w={w} | b={b:0.6f}")

    return w, b

In [ ]:
def predict(X, w, b):
    return X @ w + b

In [ ]:
# Usage example
X = np.array([
    [1, 2],
    [2, 3],
    [3, 4],
    [4, 5],
], dtype=float)

y = np.array([6, 10, 12, 23], dtype=float)

print("X shape:", X.shape, "| y shape:", y.shape)

w, b = gradient_descent(
    X, y,
    lr=0.001,
    epochs=1000,
    debug_every=100,
)

print("\nLearned parameters")
print("w:", w)
print("b:", b)

X_test = np.array([[5, 6], [6, 7]], dtype=float)
y_pred = predict(X_test, w, b)
print("\nX_test:")
print(X_test)
print("Predictions:", y_pred)

(4, 2) (4,)
0 mse is 193.80047896875004, paramters w:[0.038500 0.051250], b:0.012750000000000001
100 mse is 8.782391827792338, paramters w:[1.593807 2.087506], b:0.4936992330167193
200 mse is 6.477689422407822, paramters w:[1.793954 2.300350], b:0.5063963785479015
300 mse is 6.387237602795848, paramters w:[1.844496 2.312753], b:0.4682566006192434
400 mse is 6.325705968743046, paramters w:[1.878092 2.303289], b:0.4251966871458539
500 mse is 6.266565919823646, paramters w:[1.909346 2.291604], b:0.3822574194988948
600 mse is 6.209427323797611, paramters w:[1.939873 2.279855], b:0.3399821611726684
700 mse is 6.154218829402291, paramters w:[1.969858 2.268278], b:0.2984196139735879
800 mse is 6.10087519536888, paramters w:[1.999330 2.256894], b:0.2575642405869131
900 mse is 6.049333428973551, paramters w:[2.028300 2.245705], b:0.21740472133867594
w [2.056494 2.234815]
b 0.1783206893367041
X_test: [[5 6]
 [6 7]]
y_pred: [23.869678 28.160986]
